### ISSUE TITLE
Markdown links with relative path always failing

### ISSUE THREAD

**Issue by atteggiani** [UmbrellaDocs/linkspector#22] opened 2024-02-13 06:40 UTC
Hello, 
I am trying to update my CI/CD from using [Markdown link check](https://github.com/gaurav-nelson/github-action-markdown-link-check) action to Linkspector.

I set my baseURL in the configuration file, but only the absolute links get correctly evaluated, while all the markdown links that use relative paths fail. 

For example, if my root directory is structured like this:
```
-- docs
    |-- dir1
    |    |-- file1.md
    |
    |-- dir2
         |-- file2.md
```
in the the `file1.md` a link formatted as:

- `../dir2/file2` will fail ❌
-  `/dir2/file2` will succeed ✅

However, they both are valid links.

Am I missing something?
Is there a way to make links with a relative path not being falsely detected as failing?

Thank you!

**Comment by gaurav-nelson** [comment] 2024-02-20 01:20
Thank you for testing and creating the issue @atteggiani Looks like a bug. I'll do a fix.

**Comment by gaurav-nelson** [comment] 2024-02-26 11:25
UPdATE: On inspecting this further, I found that the issue needs some updates to the logic on how linkspector is processing links. The issue is that path.join(__dirname, link.url) is not correctly resolving relative paths. __dirname is the directory where linkspector is running, not the directory of the file that contains the link. 

To resolve this issue, I'll need to separate hyperlinks checks and file links check. This will need some work.

**Closed** 2024-05-05 06:45 UTC
Labels: bug

**Comment by matifali** [comment] 2024-06-22 20:39
is baseURL a required paarmeter? What if we are adding new docs that are not yet published?

**Comment by gaurav-nelson** [comment] 2024-06-23 22:38
@matifali 
> is `baseURL` a required parameter?

No, it is not a required parameter. I'll update the README to reflect this. 

> What if we are adding new docs that are not yet published?

If you are specifying links to the new doc set in your docs with `[sample](/new-link.md)` you can specify `baseURL` with the dir path, for example: `baseUrl: ./new-folder/new-docs`. Try that and create an issue if that doesn't work.
